version: "3.5"

services:
  app:
    image: yago/${PROJECT_NAME}:latest
    container_name: ${PROJECT_NAME}-app
    build: .
    env_file: .env
    restart: always
    hostname: app
    tty: true
    cap_add:
      - ALL
    ports:
      - 8091:8091
    networks:
      - integrate_back

networks:
  integrate_back:
    name: integrate_back
    driver: bridge
